#!/bin/sh
sed "s/NOW/`date -Iseconds -u`/" graph-with-scala-dep.json > to-submit.json

curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN"\
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/bigdaz/test-dependency-graph-2/dependency-graph/snapshots \
    -d @to-submit.json
