name: 'Gradle Dependency Submission'

inputs:
  build-root-directory:
    required: false
  cache-encryption-key:
    required: false

runs:
  using: "composite"
  steps:
    - uses: gradle/gradle-build-action@main
      with:
        dependency-graph: generate-and-submit
        build-root-directory: ${{ inputs.build-root-directory }}
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        arguments: |
          --no-configure-on-demand
          --dependency-verification=off
          :ForceDependencyResolutionPlugin_resolveAllDependencies
