name: Resusable workflow for dependency submission

on:
  workflow_call:
    inputs:
      build-root-directory:
        required: false
        type: string

jobs:
  callable-generate-and-submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/gradle-build-action@v3-beta
      with:
        dependency-graph: generate-and-submit
        build-root-directory: ${{ inputs.build-root-directory }}
        arguments: |
          --no-configure-on-demand
          --dependency-verification=off
          :ForceDependencyResolutionPlugin_resolveAllDependencies
