name: Reusable workflow generate and submit dependency graph

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  call-generate-and-submit-dependency-graph:
    uses: ./.github/workflows/callable-dependency-submission.yml
