name: Composite action generate and submit dependency graph

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  composite-generate-and-submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/dependency-submission
